In [ ]:
# 패키지 업로드
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

### 1. 결측값/중복값 처리 
한국환경공단에서 발표한 미세먼지 관련 자료를 분석해보겠습니다. <p>
<p>finedust.csv 파일을 사용 <p>
(이 파일은 공공기관 파일로, 인코딩이 utf-8이 아닌 cp949로 되어 있습니다)

In [ ]:
df = pd.read_csv('finedust.csv', encoding= 'cp949')

1-1) finedust.csv를 위에서부터 10행 출력해주세요.

측정일자   측정시간  지역  지역명   도로명                    시작점  \
0  2021-07-01   9:44  서울  구로구   부일로    서울특별시 구로구 궁동 197-10   
1  2021-07-01  10:04  서울  구로구  서해안로    서울특별시 구로구 항동 211-22   
2  2021-07-01  10:28  서울  구로구   중앙로     서울특별시 구로구 고척동 63-5   
3  2021-07-01  10:35  서울  구로구   고척로    서울특별시 구로구 고척동 186-4   
4  2021-07-01  11:04  서울  구로구   오리로         서울특별시 구로구 궁동 5   
5  2021-07-01  11:49  서울  구로구   금오로     경기도 광명시 옥길동 667-21   
6  2021-07-01  11:57  서울  구로구   천왕로    서울특별시 구로구 천왕동 14-44   
7  2021-07-01  12:09  서울  구로구   개봉로    서울특별시 구로구 개봉동 372-1   
8  2021-07-01  12:23  서울  구로구   공원로  서울특별시 구로구 신도림동 422-10   
9  2021-07-01  12:30  서울  NaN   NaN   서울특별시 구로구 구로동 136-14   

                    종점    기온    습도  재비산먼지 평균농도  오염범례  
0     서울특별시 구로구 온수동 56  28.0  57.0        27.0  매우좋음  
1  서울특별시 구로구 개봉동 243-2  28.0  58.0        18.0  매우좋음  
2   서울특별시 구로구 고척동 1-15  29.0  54.0        33.0  매우좋음  
3   서울특별시 구로구 오류동 6-41  29.0  54.0        19.0  매우좋음  
4                  NaN  29.0  56.0        23.0  매우좋음  
5                  NaN  31.0   NaN        49.0  매우좋음  
6                  NaN  31.0  50.0        22.0  매우좋음  
7                  NaN  31.0  49.0        21.0  매우좋음  
8                  NaN  31.0  48.0        29.0  매우좋음  
9                  NaN  32.0   NaN        15.0  매우좋음

1-2) 컬럼 별 결측치 개수를 구하세요.

측정일자            3
측정시간            8
지역              9
지역명             9
도로명           194
시작점           151
종점             63
기온             12
습도             32
재비산먼지 평균농도      4
오염범례           27
dtype: int64

1-3) '도로명', '시작점', '종점' 컬럼을 삭제해주세요. <p>
(결측값 데이터 처리 - 데이터 제거) <p>
hint) 컬럼 기준 thresh 사용

측정일자   측정시간   지역  지역명         기온    습도  재비산먼지 평균농도  오염범례
0    2021-07-01   9:44   서울  구로구  28.000000  57.0        27.0  매우좋음
1    2021-07-01  10:04   서울  구로구  28.000000  58.0        18.0  매우좋음
2    2021-07-01  10:28   서울  구로구  29.000000  54.0        33.0  매우좋음
3    2021-07-01  10:35   서울  구로구  29.000000  54.0        19.0  매우좋음
4    2021-07-01  11:04   서울  구로구  29.000000  56.0        23.0  매우좋음
..          ...    ...  ...  ...        ...   ...         ...   ...
297  2021-07-07  14:17   경기  화성시  29.000000  96.0        10.0  매우좋음
298  2021-07-07  14:27   경기  화성시  29.000000  94.0        86.0    좋음
299  2021-07-07  14:36   경기  화성시  29.000000  94.0        15.0  매우좋음
300         NaN    NaN  NaN  NaN        NaN   NaN         NaN   NaN
301         NaN    NaN  NaN  NaN  28.290657   NaN         NaN   NaN

[302 rows x 8 columns]

1-4) '측정 일자', '측정 시간', '지역', '지역명'의 결측값을 바로 아래 데이터로 대치해주세요. <p>
(결측값 데이터 처리 - 데이터 대치)

1-5) '기온', '습도'의 결측값은 각 열의 평균값으로 대치해주세요 <p>
(결측값 데이터 처리 - 데이터 대치)

1-6) '오염범례'의 결측값은 최빈값을 먼저 파악한 뒤, 최빈값으로 대치해주세요.  <p>
(결측값 데이터 처리 - 데이터 대치)

매우좋음    218
좋음       40
보통        9
나쁨        6
매우나쁨      2
Name: 오염범례, dtype: int64


1-7) '지역명'이 중복되는 데이터는 가장 마지막 데이터만 남겨서 중복값을 처리해주세요. <p>
(중복값 데이터 처리)

측정일자   측정시간   지역      지역명         기온          습도  재비산먼지 평균농도  오염범례
0    2021-07-01   9:44   서울      구로구  28.000000   57.000000        27.0  매우좋음
17   2021-07-01  10:25   인천      부평구  32.000000   46.000000         NaN  매우좋음
30   2021-07-01  10:01   서울      금천구  29.000000   78.000000         2.0  매우좋음
38   2021-07-01  12:50   인천       동구  30.000000   72.000000        46.0  매우좋음
45   2021-07-01  10:29   경기  용인시 수지구  28.000000   86.000000         9.0  매우좋음
47   2021-07-01  10:50   경기  용인시 기흥구  30.000000   79.000000         7.0  매우좋음
65   2021-07-02   9:34   경기      파주시  26.000000   70.000000       120.0    보통
82   2021-07-02  10:11   경기      하남시  26.000000   91.000000        20.0  매우좋음
97   2021-07-02  10:40   경기      안성시  26.000000   87.000000        27.0  매우좋음
142  2021-07-05  10:12   서울      종로구  28.290657   94.000000        58.0    좋음
157  2021-07-05   9:46   경기      시흥시  24.000000   93.000000       196.0    나쁨
175  2021-07-05  10:35   경기  용인시 처인구  26.000000   87.000000        21.0  매우좋음
191  2021-07-06  10:10   경기  안산시 상록구  28.000000   59.000000        67.0  매우좋음
194  2021-07-06  11:14   경기  안산시 단원구  28.000000   58.000000        18.0  매우좋음
204  2021-07-06  10:18   서울      송파구  29.000000   79.000000        15.0  매우좋음
239  2021-07-06  10:44   경기      구리시  27.000000   75.640741        31.0  매우좋음
262  2021-07-07   9:21   경기      부천시  29.000000   94.000000        14.0  매우좋음
279  2021-07-07  10:37   경기      화성시  27.000000  100.000000       200.0    나쁨
300         NaN    NaN  NaN      NaN  28.290657   75.640741         NaN  매우좋음

### 2.레이블 인코딩
Seaborn 패키지에 있는 titanic 데이터를 이용해 레이블 인코딩을 진행해보도록 하겠습니다. <p>


In [ ]:
from sklearn.preprocessing import LabelEncoder

titanic = sns.load_dataset('titanic')
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

2-1) titanic에 있는 class 컬럼을 레이블 인코딩해서 c_labels에 저장해주세요



array([2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 0, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0,
       2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,

2-2) 레이블 인코딩해준 class 컬럼의 각 범주가 어떤 숫자로 변환되었는지 for문과 enumerate를 통해 확인해주세요.

First -> 0
Second -> 1
Third -> 2


2-3) 인코딩해준 값 c_labels을 다시 디코딩해주세요

array(['Third', 'First', 'Third', 'First', 'Third', 'Third', 'First',
       'Third', 'Third', 'Second', 'Third', 'First', 'Third', 'Third',
       'Third', 'Second', 'Third', 'Second', 'Third', 'Third', 'Second',
       'Second', 'Third', 'First', 'Third', 'Third', 'Third', 'First',
       'Third', 'Third', 'First', 'First', 'Third', 'Second', 'First',
       'First', 'Third', 'Third', 'Third', 'Third', 'Third', 'Second',
       'Third', 'Second', 'Third', 'Third', 'Third', 'Third', 'Third',
       'Third', 'Third', 'Third', 'First', 'Second', 'First', 'First',
       'Second', 'Third', 'Second', 'Third', 'Third', 'First', 'First',
       'Third', 'First', 'Third', 'Second', 'Third', 'Third', 'Third',
       'Second', 'Third', 'Second', 'Third', 'Third', 'Third', 'Third',
       'Third', 'Second', 'Third', 'Third', 'Third', 'Third', 'First',
       'Second', 'Third', 'Third', 'Third', 'First', 'Third', 'Third',
       'Third', 'First', 'Third', 'Third', 'Third', 'First', 'First',
    

### 3.원핫 인코딩
이어서 Seaborn 패키지에 있는 titanic 데이터를 이용해 원핫 인코딩을 진행해보도록 하겠습니다. <p>


In [ ]:
from sklearn.preprocessing import OneHotEncoder

titanic = sns.load_dataset('titanic')

3-1) 타이타닉에 있는 embarked 열을 원핫 인코딩해서 oh_labels에 저장해주세요

3-2) 원핫 인코딩한 결과인 embarked를 Array 형태로 출력해주세요.

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### 4. Feature Scaling
마지막 Feature Scaling은 iris 데이터셋을 활용하여 표준화와 정규화를 진행하도록 하겠습니다.  <p>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns= iris.feature_names)

4-1) iris 데이터에 대해 표준화 하기 전 평균과 분산, 표준화하고 나서의 평균과 분산을 출력하시오.

표준화하기 전
feature 평균
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 분산
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64
표준화한 이후
feature 평균
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 분산
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


4-2) iris 데이터를 정규화를 한 뒤, 최대값과 최소값을 출력해주세요.

feature 최소값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 최대값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


#수고하셨습니다! 제출 마감 날짜는 8월 31일 (수요일) 23시 59분입니다!
파일명 주의해주세요~! (10기_n주차_복습과제_홍길동)

제출 링크: : https://forms.gle/RyoD7zW5vLB4eKFh6